# Generated by Django 4.2 on 2023-05-06 10:26

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2023, 5, 6)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='experience',
            field=models.IntegerField(help_text='Number of years working in the company', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('manager', 'Manager'), ('senior_developer', 'Senior Developer'), ('developer', 'Developer'), ('junior_developer', 'Junior Developer'), ('designer', 'Designer'), ('tester', 'Tester')], max_length=64),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_from', models.DateTimeField(default=datetime.date(2023, 5, 6))),
                ('reserved_to', models.DateTimeField(default=datetime.date(2023, 5, 6))),
                ('attendees', models.ManyToManyField(related_name='attended_reservations', to='company.employee')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_reservations', to='company.employee')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='company.room')),
            ],
        ),
    ]
