# Generated by Django 4.2 on 2023-05-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_employee_date_of_birth_alter_employee_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='creator_ip',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
